---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
spec:
  chart:
    spec:
      chart: dapr
      sourceRef:
        kind: HelmRepository
        name: dapr
      version: 1.6
  interval: 1m0s
  targetNamespace: dapr-system