---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

configMapGenerator:
  - name: staging-values
    files:
      - values.yaml=my-values.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - staging-release-values.yaml