---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
  - staging-release-values.yaml

configMapGenerator:
  - name: staging-values
    files:
      - values.yaml=my-values.yaml

configurations:
  - kustomizeconfig.yaml
