---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dagster
spec:
  chart:
    spec:
      version: 0.13.17
  valuesFrom:
    - kind: ConfigMap
      name: staging-values